import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { AccessError, authorizeCourse } from "../_shared/course-access.ts";

const COURSE_SLUG="dolor-musculoesqueletico";
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Content-Type":"application/json","Cache-Control":"private, no-store, max-age=0"};

const course={
  title:"Dolor Musculoesquelético: del mecanismo a la decisión clínica",
  subtitle:"Curso interactivo para comprender, clasificar con prudencia y tomar decisiones clínicas bajo incertidumbre.",
  modules:[
    {title:"Módulo 1 · Fundamentos del dolor",purpose:"Construir un lenguaje común y separar experiencia dolorosa, nocicepción y daño tisular.",journeys:[
      {id:"pain-01",title:"Dolor, nocicepción y experiencia",clinicalQuestion:"¿Qué estamos describiendo realmente cuando una persona dice que le duele?",learningOutcomes:["Diferenciar dolor de nocicepción.","Reconocer que intensidad de dolor y daño no son equivalentes.","Usar lenguaje clínico no amenazante."],keyConcepts:["Dolor como experiencia multidimensional.","Nocicepción como proceso neural distinto del dolor.","Contexto, expectativas y aprendizaje modifican la experiencia."],canConclude:["La evaluación del dolor requiere integrar información sensorial, funcional, contextual y psicosocial."],cannotConclude:["Una puntuación alta de dolor no identifica por sí sola una lesión grave.","Una imagen estructural no explica por sí sola la experiencia dolorosa."],limitations:["Los mecanismos son hipótesis clínicas revisables, no etiquetas absolutas."],lab:"Reformula tres explicaciones biomédicas amenazantes en mensajes clínicos precisos y no alarmistas.",case:"Persona con dolor lumbar intenso, resonancia con cambios degenerativos y examen neurológico sin déficit progresivo. Explica qué información necesitas antes de atribuir el dolor a la imagen.",decisionQuestions:["¿Qué datos aumentan o disminuyen preocupación por patología grave?","¿Qué comunicarías sobre la imagen?"],reflection:"¿Qué supuestos tuyos sobre dolor y daño cambian después de esta unidad?",feedbackCriteria:["Distingue dolor de nocicepción.","Evita causalidad estructural no demostrada.","Explicita incertidumbre."],source:"IASP terminology; ICD-11 pain classification; literatura contemporánea sobre dolor musculoesquelético."},
      {id:"pain-02",title:"Curso temporal: agudo, subagudo y persistente",clinicalQuestion:"¿Qué cambia clínicamente cuando el dolor persiste en el tiempo?",learningOutcomes:["Distinguir categorías temporales sin reducir la evaluación a duración.","Reconocer factores de recuperación y persistencia.","Planificar reevaluación longitudinal."],keyConcepts:["El tiempo es una dimensión clínica, no un mecanismo.","Persistencia no implica necesariamente daño persistente.","Trayectoria funcional y respuesta al tratamiento importan."],lab:"Construye una línea de tiempo clínica con síntomas, función, sueño, actividad, eventos vitales y tratamientos.",case:"Persona con dolor cervical de 10 semanas, alta preocupación y reducción marcada de actividad.",decisionQuestions:["¿Qué factores pueden influir en la persistencia?","¿Qué resultados seguirías semana a semana?"],reflection:"¿Qué perderías si solo clasificaras por duración?",source:"ICD-11; marcos contemporáneos de dolor persistente."}
    ]},
    {title:"Módulo 2 · Fenotipos y mecanismos",purpose:"Razonar sobre contribuciones nociceptivas, neuropáticas y nociplásticas sin convertirlas en diagnósticos rígidos.",journeys:[
      {id:"pain-03",title:"Predominio nociceptivo",clinicalQuestion:"¿Cuándo una presentación es más compatible con predominio nociceptivo?",learningOutcomes:["Reconocer rasgos compatibles.","Integrar comportamiento mecánico, irritabilidad y carga.","Evitar inferir tejido específico sin sustento."],keyConcepts:["Concordancia clínica.","Relación carga-síntoma.","Distribución anatómicamente plausible."],lab:"Analiza qué hallazgos apoyan, contradicen o no informan una hipótesis nociceptiva.",case:"Dolor de rodilla relacionado con carga, patrón localizado y variación predecible con actividad.",decisionQuestions:["¿Qué hipótesis mantienes abiertas?","¿Qué intervención usarías como experimento clínico?"],reflection:"¿Qué diferencia hay entre identificar predominio nociceptivo e identificar una estructura exacta?",source:"IASP; literatura de clasificación de mecanismos de dolor musculoesquelético."},
      {id:"pain-04",title:"Dolor neuropático y dolor radicular",clinicalQuestion:"¿Cómo evitar llamar neuropático a cualquier dolor irradiado?",learningOutcomes:["Reconocer distribución neuroanatómica plausible.","Integrar síntomas, signos sensoriales y examen neurológico.","Distinguir dolor radicular de dolor referido no neuropático."],keyConcepts:["Historia + distribución + signos neurológicos.","Probabilidad diagnóstica gradual.","Un cuestionario de screening no sustituye examen clínico."],lab:"Compara tres perfiles de dolor irradiado y justifica cuál requiere mayor sospecha neuropática.",case:"Dolor lumbar con irradiación distal, parestesias y déficit sensitivo concordante.",decisionQuestions:["¿Qué elementos aumentan la probabilidad de dolor neuropático?","¿Qué hallazgos obligan a escalar la evaluación?"],reflection:"¿Qué error clínico produce usar solo palabras como ardor u hormigueo?",source:"NeuPSIG grading system; IASP neuropathic pain terminology."}
    ]},
    {title:"Módulo 3 · Nociplasticidad y dolor persistente",purpose:"Comprender la nociplasticidad como descriptor de mecanismo probable y no como explicación total de la persona.",journeys:[
      {id:"pain-05",title:"Nociplasticidad: criterios y cautelas",clinicalQuestion:"¿Qué evidencia clínica necesitamos antes de considerar un predominio nociplástico?",learningOutcomes:["Reconocer rasgos clínicos compatibles.","Evitar usar nociplástico como diagnóstico de descarte apresurado.","Integrar hipersensibilidad, distribución y comorbilidades."],keyConcepts:["Hiperalgesia y sensibilidad aumentada.","Distribución más amplia o menos proporcional.","Contribuciones de sueño, estrés, fatiga y contexto."],lab:"Construye una matriz de evidencia a favor, en contra e insuficiente para nociplasticidad.",case:"Dolor musculoesquelético persistente multirregional, sueño no reparador y sensibilidad aumentada al examen.",decisionQuestions:["¿Qué debes descartar primero?","¿Qué hallazgos apoyarían una hipótesis nociplástica?"],reflection:"¿Cómo comunicarías esta hipótesis sin sugerir que el dolor es imaginario?",source:"IASP nociplastic pain terminology; criterios clínicos publicados para dolor musculoesquelético nociplástico."},
      {id:"pain-06",title:"Fenotipos mixtos",clinicalQuestion:"¿Puede una persona presentar más de un mecanismo relevante al mismo tiempo?",learningOutcomes:["Reconocer coexistencia de mecanismos.","Priorizar el mecanismo clínicamente dominante.","Revisar la hipótesis según evolución."],keyConcepts:["Los fenotipos pueden coexistir.","Dominancia puede cambiar en el tiempo.","La clasificación sirve para orientar decisiones, no para encasillar."],lab:"Jerarquiza hipótesis en un caso con dolor local, síntomas neurales y sensibilidad generalizada.",case:"Dolor lumbar persistente con componente mecánico, irradiación intermitente y sueño muy alterado.",decisionQuestions:["¿Cuál es tu hipótesis principal?","¿Qué información podría cambiarla?"],reflection:"¿Qué ventaja tiene trabajar con hipótesis jerarquizadas?",source:"Marcos contemporáneos de clasificación de mecanismos y razonamiento clínico."}
    ]},
    {title:"Módulo 4 · Evaluación y cuestionarios",purpose:"Seleccionar medidas por propósito clínico y comprender qué puede y qué no puede decir cada instrumento.",journeys:[
      {id:"pain-07",title:"Dolor, función e interferencia",clinicalQuestion:"¿Qué debemos medir además de intensidad de dolor?",learningOutcomes:["Seleccionar medidas de intensidad, función e interferencia.","Interpretar cambio clínico con cautela.","Evitar convertir PROMs en diagnósticos."],keyConcepts:["NPRS/VAS para intensidad.","PSFS y medidas regionales para función.","PROMs complementan, no reemplazan, conversación y examen."],lab:"Diseña un set mínimo de resultados para un paciente con dolor persistente.",case:"Paciente informa 7/10 de dolor pero ha retomado caminatas y trabajo parcial.",decisionQuestions:["¿Ha mejorado?","¿Qué resultados adicionales necesitas?"],reflection:"¿Por qué dolor y recuperación no siempre se mueven en paralelo?",source:"Instrumentos de resultado clínico ampliamente utilizados en dolor musculoesquelético."},
      {id:"pain-08",title:"Screening neuropático y psicosocial",clinicalQuestion:"¿Cómo usar cuestionarios sin delegarles el razonamiento clínico?",learningOutcomes:["Distinguir screening de diagnóstico.","Seleccionar instrumentos según pregunta clínica.","Integrar resultados con entrevista y examen."],keyConcepts:["DN4 y painDETECT son herramientas de screening.","PCS, TSK y escalas de autoeficacia exploran constructos específicos.","Puntos de corte dependen de validación y contexto."],lab:"Para cada cuestionario, escribe qué pregunta responde y qué conclusión no permite.",case:"Paciente con alta puntuación en catastrofismo y baja autoeficacia.",decisionQuestions:["¿Qué cambiaría en tu comunicación?","¿Qué no deberías concluir automáticamente?"],reflection:"¿Qué riesgo existe al convertir un cuestionario en una etiqueta?",source:"Literatura original y validaciones de DN4, painDETECT, PCS, TSK y PSEQ."}
    ]},
    {title:"Módulo 5 · Razonamiento clínico y fiabilidad",purpose:"Aprender a distinguir acuerdo, validez, utilidad clínica y precisión aparente.",journeys:[
      {id:"pain-09",title:"Fiabilidad interexaminador",clinicalQuestion:"¿Qué significa realmente que dos clínicos estén de acuerdo?",learningOutcomes:["Diferenciar acuerdo porcentual y kappa.","Reconocer que fiabilidad no equivale a validez.","Interpretar sistemas de clasificación con prudencia."],keyConcepts:["Acuerdo observado.","Acuerdo corregido por azar.","Reproducibilidad ≠ exactitud diagnóstica."],lab:"Analiza un estudio con 72% de acuerdo global y un acuerdo exacto menor para combinaciones complejas. Explica por qué ambos resultados pueden coexistir.",case:"Dos fisioterapeutas coinciden en el patrón dominante, pero difieren en subclasificaciones adicionales.",decisionQuestions:["¿Qué conclusión permite la fiabilidad?","¿Qué conclusión no permite?"],reflection:"¿Cómo afecta la complejidad de una taxonomía a su reproducibilidad?",source:"Petersen et al. Inter-tester reliability of a new diagnostic classification system for non-specific low back pain."},
      {id:"pain-10",title:"Hipótesis revisables y probabilidad",clinicalQuestion:"¿Cómo decidir sin fingir certeza diagnóstica?",learningOutcomes:["Construir hipótesis jerarquizadas.","Buscar datos que puedan falsarlas.","Usar respuesta clínica para actualizar decisiones."],keyConcepts:["Probabilidad pretest.","Datos concordantes y discordantes.","Reevaluación como parte del diagnóstico funcional."],lab:"Escribe una hipótesis principal, dos alternativas y qué dato haría cambiar cada una.",case:"Paciente con dolor de hombro de presentación ambigua y varias pruebas especiales positivas.",decisionQuestions:["¿Qué pesa más: cantidad de pruebas o coherencia del patrón?","¿Cómo usarías un ensayo terapéutico?"],reflection:"¿Qué cambia cuando dejas de buscar una etiqueta única?",source:"Razonamiento clínico probabilístico y literatura de utilidad diagnóstica."}
    ]},
    {title:"Módulo 6 · Intervención y comunicación",purpose:"Traducir la formulación clínica en educación, exposición, ejercicio y decisiones compartidas.",journeys:[
      {id:"pain-11",title:"Educación y reconceptualización",clinicalQuestion:"¿Qué educación ayuda y qué educación puede aumentar amenaza?",learningOutcomes:["Adaptar mensajes a la persona.","Evitar explicaciones reduccionistas.","Vincular educación con acción y función."],keyConcepts:["Validar la experiencia sin reforzar daño.","Explicar incertidumbre con claridad.","Educación como parte de una intervención activa."],lab:"Construye una explicación de 60 segundos para dolor persistente que conecte seguridad, función y plan.",case:"Paciente teme flexionarse porque cree que su columna se está desgastando.",decisionQuestions:["¿Qué lenguaje evitarías?","¿Qué experimento funcional propondrías?"],reflection:"¿Qué diferencia hay entre informar y producir aprendizaje clínicamente útil?",source:"Literatura de educación en dolor y comunicación clínica."},
      {id:"pain-12",title:"Ejercicio, exposición y dosificación",clinicalQuestion:"¿Cómo usar movimiento y ejercicio cuando existe dolor?",learningOutcomes:["Dosificar según capacidad, irritabilidad y objetivos.","Distinguir respuesta tolerable de deterioro clínico.","Progresar exposición con criterios explícitos."],keyConcepts:["Objetivos funcionales.","Carga graduada.","Monitoreo de respuesta y recuperación."],lab:"Diseña una progresión de cuatro semanas con criterios de avance, mantención y retroceso.",case:"Persona con dolor persistente y miedo a cargar peso desde el suelo.",decisionQuestions:["¿Qué variable progresarías primero?","¿Cómo acordarías una respuesta aceptable al dolor?"],reflection:"¿Cómo cambia tu intervención cuando el objetivo es recuperar capacidad y no perseguir dolor cero?",source:"Guías contemporáneas de manejo musculoesquelético y ejercicio terapéutico."}
    ]}
  ]
};

const library=[
 {title:"IASP Terminology",module:"Módulos 1–3",sourceType:"Terminología",tier:"Núcleo",summary:"Marco terminológico para dolor, nocicepción, dolor neuropático y nociplástico.",clinicalUse:"Definiciones y comunicación clínica.",caution:"Las definiciones no sustituyen criterios diagnósticos ni razonamiento clínico."},
 {title:"ICD-11 classification of chronic pain",module:"Módulo 1",sourceType:"Clasificación",tier:"Núcleo",summary:"Clasificación internacional del dolor crónico.",clinicalUse:"Contextualizar dolor crónico primario y secundario.",caution:"Clasificación administrativa/diagnóstica no equivale a mecanismo individual."},
 {title:"NeuPSIG grading system for neuropathic pain",module:"Módulo 2",sourceType:"Marco diagnóstico",tier:"Núcleo",summary:"Sistema de gradación para aumentar o disminuir probabilidad de dolor neuropático.",clinicalUse:"Estructurar historia y examen neurológico.",caution:"Requiere integración clínica; no depende de un único descriptor."},
 {title:"Clinical criteria for nociplastic musculoskeletal pain",module:"Módulo 3",sourceType:"Criterios clínicos",tier:"Núcleo",summary:"Propuesta clínica para reconocer presentaciones compatibles con nociplasticidad.",clinicalUse:"Fenotipado razonado.",caution:"No usar como etiqueta de descarte ni explicación total."},
 {title:"Petersen et al. Inter-tester reliability in non-specific low back pain",module:"Módulo 5",sourceType:"Estudio de fiabilidad",tier:"Aplicado",summary:"Ejemplo para diferenciar acuerdo global, acuerdo exacto y fiabilidad de clasificaciones.",clinicalUse:"Interpretación crítica de reproducibilidad.",caution:"Fiabilidad no demuestra validez diagnóstica."}
];

serve(async(req)=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});
 if(req.method!=="POST")return new Response(JSON.stringify({message:"Método no permitido."}),{status:405,headers:corsHeaders});
 try{
  const body=await req.json().catch(()=>({}));
  if(String(body.courseSlug||"").trim()!==COURSE_SLUG)return new Response(JSON.stringify({message:"Curso no autorizado."}),{status:403,headers:corsHeaders});
  const {access}=await authorizeCourse(req.headers.get("Authorization")||"",COURSE_SLUG);
  return new Response(JSON.stringify({access,course,library}),{status:200,headers:corsHeaders});
 }catch(error){const status=error instanceof AccessError?error.status:500;const message=error instanceof Error?error.message:"Error inesperado.";console.error("pain-content error",error);return new Response(JSON.stringify({message}),{status,headers:corsHeaders})}
});
