const C=window.KINECHECK_CONFIG||{};
const EXPECTED_COURSE="dolor-musculoesqueletico";
const SESSION_KEY="kinecheck_course_session_v2:dolor-musculoesqueletico";
const LEGACY_SESSION_KEY="kinecheck_course_session_v1:dolor-musculoesqueletico";
const $=selector=>document.querySelector(selector);
const shell=$("#access-shell"),profileShell=$("#profile-shell"),root=$("#root"),msg=$("#auth-message"),busy=$("#access-progress"),ecosystemEntry=$("#ecosystem-entry"),retryButton=ecosystemEntry?.querySelector(".ecosystem-retry"),signOut=$("#sign-out");
let starting=false;
function configuredCorrectly(){return Boolean(C.supabaseUrl&&C.supabaseAnonKey&&C.contentFunction&&C.courseSlug===EXPECTED_COURSE)}
function headers(token){const h={apikey:C.supabaseAnonKey,"Content-Type":"application/json"};if(token)h.Authorization=`Bearer ${token}`;return h}
async function fetchWithTimeout(url,options={},timeout=15000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{return await fetch(url,{...options,cache:"no-store",signal:controller.signal})}finally{clearTimeout(timer)}}
async function api(path,options={}){const response=await fetchWithTimeout(`${C.supabaseUrl}${path}`,{...options,headers:{...headers(options.token),...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok){const e=new Error(data.message||data.error||"Solicitud rechazada");e.status=response.status;throw e}return data}
function normalizeSession(value){if(!value?.access_token)return null;const expiresAt=Number(value.expires_at||0);if(expiresAt&&expiresAt<=Math.floor(Date.now()/1000)+15)return null;if(value.product&&value.product!==EXPECTED_COURSE)return null;return{access_token:String(value.access_token),expires_at:expiresAt||null,expires_in:Number(value.expires_in||0)||null,token_type:value.token_type||"bearer",handoff_access_only:true,product:EXPECTED_COURSE}}
function readJson(storage,key){try{return normalizeSession(JSON.parse(storage.getItem(key)||"null"))}catch{return null}}
function clearSession(){try{sessionStorage.removeItem(SESSION_KEY);sessionStorage.removeItem(LEGACY_SESSION_KEY);localStorage.removeItem(SESSION_KEY);localStorage.removeItem(LEGACY_SESSION_KEY)}catch{}}
function readSession(){return readJson(sessionStorage,SESSION_KEY)||readJson(localStorage,LEGACY_SESSION_KEY)}
async function waitForSession(timeoutMs=5000){const started=Date.now();while(Date.now()-started<timeoutMs){const s=readSession();if(s)return s;await new Promise(r=>setTimeout(r,100))}return null}
async function validateIdentity(session){const user=await api("/auth/v1/user",{method:"GET",token:session.access_token});return{...session,user}}
function show(text,error=false){if(!msg)return;msg.textContent=text;msg.className=error?"notice notice-error":"notice";msg.hidden=false}
function setBusy(value,text="Validando tu licencia de Dolor Musculoesquelético…"){if(!busy)return;busy.hidden=!value;const p=busy.querySelector("p");if(p)p.textContent=text}
function showEntry(text="Abre este curso desde tu biblioteca KineCheck."){setBusy(false);if(ecosystemEntry){ecosystemEntry.hidden=false;const p=ecosystemEntry.querySelector("p");if(p)p.textContent=text}if(shell)shell.hidden=false;if(profileShell)profileShell.hidden=true;if(root)root.hidden=true}
async function invokeFunction(name,session,body={}){const response=await fetchWithTimeout(`${C.supabaseUrl}/functions/v1/${name}`,{method:"POST",headers:headers(session.access_token),body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok){const e=new Error(data.message||"No fue posible completar la solicitud.");e.status=response.status;throw e}return data}
async function loadProtectedContent(session){setBusy(true);const data=await invokeFunction(C.contentFunction,session,{courseSlug:EXPECTED_COURSE});if(!data?.course?.modules?.length)throw new Error("El contenido protegido aún no fue publicado en Supabase.");if(data?.access?.courseSlug&&data.access.courseSlug!==EXPECTED_COURSE){const e=new Error("La autorización recibida no corresponde a Dolor Musculoesquelético.");e.status=403;throw e}return data}
function openCourse(session,state,content){shell.hidden=true;profileShell.hidden=true;root.hidden=false;window.KineCheckCourse.start(session,state,content)}
async function launch(session){const content=await loadProtectedContent(session);if(window.KineCheckWatermark)await window.KineCheckWatermark.showVerifiedBuyer({user:session.user,licenseScopes:[EXPECTED_COURSE]});window.KineCheckProgress.setSession(session);let state=window.KineCheckProgress.readLocal?window.KineCheckProgress.readLocal():window.KineCheckProgress.defaultState();try{state=await window.KineCheckProgress.load()}catch{}shell.hidden=true;if(!state.profile){profileShell.hidden=false;document.querySelectorAll(".profile-option").forEach(button=>{button.onclick=()=>{state.profile=button.dataset.profile;window.KineCheckProgress.push(state);openCourse(session,state,content)}})}else openCourse(session,state,content)}
async function start(){if(starting)return;starting=true;if(msg)msg.hidden=true;if(ecosystemEntry)ecosystemEntry.hidden=true;setBusy(true,"Recibiendo tu acceso desde KineCheck…");try{if(!configuredCorrectly())throw new Error("La configuración de acceso no coincide con Dolor Musculoesquelético.");const raw=readSession()||await waitForSession();if(!raw){showEntry("No recibimos una sesión desde la biblioteca. Vuelve a Biblioteca y abre nuevamente este curso.");return}const session=await validateIdentity(raw);await launch(session)}catch(error){window.KineCheckWatermark?.hide();setBusy(false);if(error.status===401)clearSession();show(error.message||"No fue posible abrir el curso.",true);if(ecosystemEntry)ecosystemEntry.hidden=false}finally{starting=false}}
retryButton?.addEventListener("click",e=>{e.preventDefault();start()});
signOut?.addEventListener("click",()=>{window.KineCheckWatermark?.hide();clearSession();location.replace("https://kinecheck.cl/academy/#biblioteca")});
window.addEventListener("kinecheck:sso-received",()=>start());start();
